[supabase]
url      = "https://blczadrtgbgkrjewbqxo.supabase.co"
anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsY3phZHJ0Z2Jna3JqZXdicXhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc4MzcyOTYsImV4cCI6MjEwMzQxMzI5Nn0.sQaOE8MQ8lOenmZymx9d7_cz0XUyD2lzCoC6FQmw6uY"
